### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by lycly** [frainzy1477/clashr#7]
之前的0.16.1是可以正常运行的，0.16.2版本点击启动，会有配置文件报错，日志为
 level=fatal msg="Parse config error: yaml: line 871: could not find expected ':'" ，看了下是因为有个规则格式错误，但是我自己用自定义的配置（检查无误）上传后，再启动，还是会有这种问题。

**Comment by frainzy1477** [comment]
> 之前的0.16.1是可以正常运行的，0.16.2版本点击启动，会有配置文件报错，日志为
> level=fatal msg="Parse config error: yaml: line 871: could not find expected ':'" ，看了下是因为有个规则格式错误，但是我自己用自定义的配置（检查无误）上传后，再启动，还是会有这种问题。

你的config.yaml问题

**Comment by lycly** [comment]
我用的ssr订阅，config是自动生成的，然后启动，就会显示那个错误。我自己改了下config.yaml,检查无误后，又上传自定义配置，点启动，可配置文件有的地方它会自动变动。

**Comment by frainzy1477** [comment]
先清除节点   然后v2ssr2clash就要输入你的ssr订阅地址，不要加api地址
![Screenshot_13](https://user-images.githubusercontent.com/49537471/68068003-b1188880-fd8a-11e9-9f45-3b5a6c2b9398.png)

**Comment by lycly** [comment]
还有个问题，就是luci-app里的wget-nossl,我用的是原版openwrt，配置了软件源为https下载方式，每回安装的时候都要切换回http，然后才能安装，而且这个安装也是佛系，一会儿成功，一会儿失败，失败显示r如下，可是我前提已经opkg update了
Installing luci-app-clash (1.2.6-1) to root...
Installing wget-nossl (1.19.5-3) to root...
Downloading http://mirrors.ustc.edu.cn/lede/releases/18.06.4/packages/x86_64/packages/wget-nossl_1.19.5-3_x86_64.ipk
Collected errors:
 * opkg_download: Failed to download http://mirrors.ustc.edu.cn/lede/releases/18.06.4/packages/x86_64/packages/wget-nossl_1.19.5-3_x86_64.ipk, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_install_pkg: Failed to download wget-nossl. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package luci-app-clash.

**Comment by frainzy1477** [comment]
你应该要安装libustream-openssl  wget 

libustream-openssl
https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/base/libustream-openssl20150806_2019-08-17-e8f9c22d-1_x86_64.ipk

wget ssl
https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/packages/wget_1.20.3-2_x86_64.ipk

wget no ssl
https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/packages/wget-nossl_1.20.3-2_x86_64.ipk

**Comment by frainzy1477** [comment]
我在用的
X86
src/gz openwrt_core https://openwrt.proxy.ustclug.org/snapshots/targets/x86/64/packages
src/gz openwrt_base https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/base
src/gz openwrt_luci https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/luci
src/gz openwrt_packages https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/packages
src/gz openwrt_routing https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/routing


![image](https://user-images.githubusercontent.com/49537471/68068323-67ca3800-fd8e-11e9-8833-b6713522c6b5.png)

**Comment by lycly** [comment]
我安装了呀，wget默认有的，为了支持https，我安装了libustream-openssl ca-bundle

**Comment by lycly** [comment]
你的软件源是开发版，我的是稳定版。请问下你的是lean还是lede官方的固件？

**Comment by frainzy1477** [comment]
改用我的发行版软件源 然后opkg update, 然后重安装luci-app-clash
lean或lede官方可以试试, 先备份你的发行版软件源

src/gz openwrt_core https://openwrt.proxy.ustclug.org/snapshots/targets/x86/64/packages
src/gz openwrt_base https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/base
src/gz openwrt_luci https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/luci
src/gz openwrt_packages https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/packages
src/gz openwrt_routing https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/routing

**Comment by lycly** [comment]
真的是佛系，我重新刷了下机，又安装成功了

**Comment by frainzy1477** [comment]
> 真的是佛系，我重新刷了下机，又安装成功了
好的
